name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i
    - run: npm run lint:ci
    - run: npm run test:ci
    - run: npm run build
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
